env_name: "HalfCheetah-v2"
dim: 1
change_param_names: [
            "worldfriction"
        ]
change_param_min: [
            0.1
        ]
change_param_max: [
            3.0
        ]
xml_file: "half_cheetah.xml"
