env_name: "HalfCheetah-v2"
dim: 3
change_param_names: [
            "worldfriction", "torsomass", "backthighmass"
        ]
change_param_min: [
            0.1, 0.1, 0.1
        ]
change_param_max: [
            4.0, 7.0, 3.0
        ]
xml_file: "half_cheetah.xml"
