env_name: "Hopper-v2"
dim: 2
change_param_names: [
            "worldfriction", "torsomass"
        ]
change_param_min: [
            0.1, 0.1
        ]
change_param_max: [
            3.0, 3.0
        ]
xml_file: "hopper.xml"
