env_name: "HumanoidStandup-v2"
dim: 3
change_param_names: [
            "torsomass", "rightfootmass", "leftthighmass"
        ]
change_param_min: [
            0.1, 0.1, 0.1
        ]
change_param_max: [
            16.0, 5.0, 8.0
        ]
xml_file: "humanoidstandup.xml"
