env_name: "HumanoidStandup-v2"
dim: 1
change_param_names: [
            "torsomass"
        ]
change_param_min: [
            0.1
        ]
change_param_max: [
            16.0
        ]
xml_file: "humanoidstandup.xml"
