env_name: "InvertedPendulum-v2"
dim: 2
change_param_names: [
            "polemass", "cartmass"
        ]
change_param_min: [
            1.0, 1.0
        ]
change_param_max: [
            31.0, 11.0
        ]
xml_file: "inverted_pendulum.xml"
