env_name: "Walker2d-v2"
dim: 1
change_param_names: [
            "worldfriction"
        ]
change_param_min: [
            0.1
        ]
change_param_max: [
            4.0
        ]
xml_file: "walker2d.xml"
