env_name: "Walker2d-v2"
dim: 3
change_param_names: [
            "worldfriction", "torsomass", "thighmass"
        ]
change_param_min: [
            0.1, 0.1, 0.1
        ]
change_param_max: [
            4.0, 5.0, 6.0
        ]
xml_file: "walker2d.xml"
